#!/bin/bash
#
# Example FaxDispatch script
# See FAXRCVD(8) for documentation
#
# CALLID fields populated by GOfax.IP:
# $CALLID1 -> Callerid-Number
# $CALLID2 -> Callerid-Name
# $CALLID3 -> Recipent (SIP To-User)
# $CALLID4 -> Gateway name
#
# Extra environment set by gofaxd:
# $HANGUPCAUSE   -> FreeSWITCH Hangup Cause (text)
# $TRANSFER_RATE -> SpanDSP Transfer Rate (e.g. 9600 / 14400)

# Use TRANSFER_RATE as SIGNALRATE for email templates
# (SpanDSP doesn't fill the FaxRecvParams TIFF Tag,
# so SIGNALRATE is 0 bit/s by default)
SIGNALRATE="$TRANSFER_RATE bit/s"

# Language / email template
TEMPLATE=en

# From address for all faxes / notifications
FROMADDR=faxmaster@example.com

# Recipient for faxmaster (administrative) notifications
TOADDR=faxmaster@example.com
NOTIFY_FAXMASTER=never

# Recipient for incoming fax
SENDTO=someone@example.com

# Filetype for fax attachment
FILETYPE=pdf
