#!/bin/bash
#
# Example FaxDispatch script
# See FAXRCVD(8) for documentation
#
# CALLID fields populated by GOfax.IP:
# $CALLID1 -> Callerid-Number
# $CALLID2 -> Callerid-Name
# $CALLID3 -> Recipent (SIP To-User)
#

SENDTO=someone@example.com
NOTIFY_FAXMASTER=never
FILETYPE=pdf
