#!/bin/bash
#
# Example FaxDispatch script
# See FAXRCVD(8) for documentation
#
# CALLID fields populated by GOfax.IP:
# $CALLID1 -> Callerid-Number
# $CALLID2 -> Callerid-Name
# $CALLID3 -> Recipent (SIP To-User)
#

# Language / email template
TEMPLATE=en

# From address for all faxes / notifications
FROMADDR=faxmaster@example.com

# Recipient for faxmaster (administrative) notifications
TOADDR=faxmaster@example.com
NOTIFY_FAXMASTER=never

# Recipient for incoming fax
SENDTO=someone@example.com

# Filetype for fax attachment
FILETYPE=pdf
